// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package examples

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/HumamAlhusaini/active-search/internal/model"
	"github.com/HumamAlhusaini/active-search/internal/views/components"
	"time"
)

// example
func BasicChat() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full max-w-screen-sm rounded-box mx-auto border border-base-content/30 p-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Chat(model.Chat{
			Messages: []model.ChatMessage{
				{
					AvatarURL: "/static/images/avatar.jpg",
					Sender:    "Me",
					Time:      time.Now().UTC().Add(-4 * time.Minute).Format("15:04:05"),
					Message:   "I started learning how to cook more dishes from scratch, and it's been way more satisfying than I expected. Last night, I made homemade pasta!",
					Footer:    "✓✓",
					Location:  "start",
					Class:     "chat-bubble-primary",
				},
				{
					AvatarURL: "/static/images/avatar-reverse.jpg",
					Sender:    "Myself",
					Time:      time.Now().UTC().Add(-2 * time.Minute).Format("15:04:05"),
					Message:   "That's awesome! Homemade pasta is no joke—it's a workout, too! Did you use a pasta machine, or go for the classic rolling pin method?",
					Footer:    "✓✓",
					Location:  "end",
				},
				{
					AvatarURL: "/static/images/avatar.jpg",
					Sender:    "Me",
					Time:      time.Now().UTC().Add(-1 * time.Minute).Format("15:04:05"),
					Message:   "Went old-school with the rolling pin! Took forever, but it was worth it. I made a simple marinara sauce to go with it, and honestly, it was better than what I usually order.",
					Footer:    "✓✓",
					Location:  "start",
					Class:     "chat-bubble-primary",
				},
				{
					AvatarURL: "/static/images/avatar-reverse.jpg",
					Sender:    "Myself",
					Time:      time.Now().UTC().Format("15:04:05"),
					Message:   "Love it! Next up, you've got to try ravioli. It's a bit more work, but filling them with something like ricotta and spinach makes it feel super fancy. You'll impress everyone!",
					Footer:    "✓✓",
					Location:  "end",
				},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
